[project]
name = "pdf-to-excel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.8",
    "pypdf2>=3.0.1",
    "streamlit>=1.52.2",
]
